name: Snyk Security

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read 
      security-events: write 
      actions: read 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adB

        env:
          SNYK_TOKEN: ${{ secrets.ASUBEDI_SNYK_TOKEN }}


      - name: build
        run: npm install
        env:
          SNYK_TOKEN: ${{secrets.ASUBEDI_SNYK_TOKEN}}

          

      - name: SNYK Authenticate
        run: snyk auth $SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.ASUBEDI_SNYK_TOKEN}}
          
      - name: Snyk Code test
        run: snyk code test 
        continue-on-error: true
